export enum UserAction {
  USER_LOADING_START = "USER_LOADING_START",
  USER_LOADING_END = "USER_LOADING_END",

  GET_USER_SUCCESS = "GET_USER_SUCCESS",
  GET_USER_NOT_FOUND = "GET_USER_NOT_FOUND",
  GET_USER_HTTP_INTERNAL_ERROR = "GET_USER_HTTP_INTERNAL_ERROR",
  GET_USER_ERROR = "GET_USER_ERROR",
}
