import { AppSidebar } from "@/components/Sidebar/AppSidebar";
import { SiteHeader } from "@/components/Sidebar/SiteHeader";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppContextProviders } from "@/store/context";
import { ApiProvider } from "@/store/context/ApiContext";
import type { Metadata } from "next";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <ApiProvider>
      <AppContextProviders>
        <div className="[--header-height:calc(theme(spacing.14))]">
          <SidebarProvider className="flex flex-col" defaultOpen={defaultOpen}>
            <SiteHeader />
            <div className="flex flex-1">
              <AppSidebar />
              <SidebarInset>
                <main className="px-4 py-4">{children}</main>
              </SidebarInset>
            </div>
          </SidebarProvider>
        </div>
      </AppContextProviders>
    </ApiProvider>
  );
}
