export enum MediaPodAction {
  MEDIA_PODS_LOADING_START = "MEDIA_PODS_LOADING_START",
  MEDIA_PODS_LOADING_END = "MEDIA_PODS_LOADING_END",

  GET_MEDIA_PODS_SUCCESS = "GET_MEDIA_PODS_SUCCESS",
  GET_MEDIA_PODS_NOT_FOUND = "GET_MEDIA_PODS_NOT_FOUND",
  GET_MEDIA_PODS_HTTP_INTERNAL_ERROR = "GET_MEDIA_PODS_HTTP_INTERNAL_ERROR",
  GET_MEDIA_PODS_ERROR = "GET_MEDIA_PODS_ERROR",

  GET_RECENTS_MEDIA_PODS_SUCCESS = "GET_RECENTS_MEDIA_PODS_SUCCESS",
  GET_RECENTS_MEDIA_PODS_NOT_FOUND = "GET_RECENTS_MEDIA_PODS_NOT_FOUND",
  GET_RECENTS_MEDIA_PODS_HTTP_INTERNAL_ERROR = "GET_RECENTS_MEDIA_PODS_HTTP_INTERNAL_ERROR",
  GET_RECENTS_MEDIA_PODS_ERROR = "GET_RECENTS_MEDIA_PODS_ERROR",
}
