export enum ConfigurationAction {
  CONFIGURATION_LOADING_START = "CONFIGURATIONS_LOADING_START",
  CONFIGURATION_LOADING_END = "CONFIGURATIONS_LOADING_END",

  GET_CONFIGURATION_SUCCESS = "GET_CONFIGURATION_SUCCESS",
  GET_CONFIGURATION_NOT_FOUND = "GET_CONFIGURATION_NOT_FOUND",
  GET_CONFIGURATION_HTTP_INTERNAL_ERROR = "GET_CONFIGURATION_HTTP_INTERNAL_ERROR",
  GET_CONFIGURATION_ERROR = "GET_CONFIGURATION_ERROR",
}
